package com.metaled.Utils

object ConstantUtils {
    const val USER_ID="userid"
    const val USER_MOBILE_No="mobileno"
    const val COUNTRY_CODE="countrycode"
    const val USER_TYPE="usertype"
    const val EMAIL="email"
    const val IS_LOGIN="islogin"
    const val AUTH_TOKEN="authtoken"
    const val USER_NAME="name"
    const val PASSWORD="password"
    const val LOGIN_TYPE="logintype"
    const val ADDRESS="address"
    const val ABOUT="about"
    const val IS_TOURGUIDE="tourguide"
    const val PROFILE_IMAGE="image"
    const val IMAGE_URL="image_url"
    const val IMAGE="image"
    const val EMAIL_VERIFIED_AT="email_verified_at"
    const val FACEBOOK_ID="facebook_id"
    const val GOOGLE_ID="google_id"
    const val ID="id"
    const val LAT="lat"
    const val LNG="lng"
    const val CREATED_AT="created_at"
    const val GENDER="gender"
    const val NAME="name"
    const val UPDATED_AT="updated_at"
    const val DATE_OF_BIRTH="date_of_birth"
    const val PHONE="phone"
    const val WORK_EMAIL="work_email"
    const val STATUS="status"
    const val REMEMBER_TOKEN="remember_token"
    const val LOCATION="location"


}